# 1. 넘파이 배열의 연산


## 1-1. 배열과 스칼라(상수) 간의 연산
* 같은 배열 내 요소의 합 구하기 : *numpy*.**sum**(*ndarray*, axis=0/1) : 1 - row, 0 - column
* 배열 전체 요소의 합 구하기 : *ndarray*.**sum()

In [1]:
import numpy as np

In [8]:
# 같은 배열 내 요소의 합 구하기
# 1 ~ 6 까지의 2x3 배열 생성
# row별 합
# column별 합
a = np.arange(1,7).reshape(2,3)
a, np.sum(a, axis=1), np.sum(a, axis=0)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([ 6, 15]),
 array([5, 7, 9]))

In [9]:
#배열 전체 요소의 합 구하기
a.sum()

21

* 배열과 상수의 사칙연산 -> 배열의 각 요소마다 상수의 사칙연산 적용

In [12]:
# 1 ~ 12 까지 숫자를 3x4 배열로 만든 후 상수 10으로 사칙연산하기
a = np.arange(1,13).reshape(3,4)
a, a+10, a-10, a*10, a/10
# list면 그냥 갯수가 바뀜(값이 바뀌지 않음)

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]),
 array([[-9, -8, -7, -6],
        [-5, -4, -3, -2],
        [-1,  0,  1,  2]]),
 array([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]]),
 array([[0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8],
        [0.9, 1. , 1.1, 1.2]]))

## 1-2. 브로드캐스팅

* 차원의 크기가 다른 배열끼지 산술연산이 가능하도록, 모양/차원이 다른 배열들을 변환하는것
  - 최소한 하나의 배열의 1차원인 경우
  - 두 배열의 차원의 쌍이 맞을 경우
  - 차원에 대해 행의 길이 혹은 열의 길이가 같은 겨우

In [13]:
A=np.array([[1, 2], [3, 4]])
B=np.array([1, 2])
A+B

array([[2, 4],
       [4, 6]])

In [14]:
# 갯수가 안 맞으면 오류남
A=np.array([[1, 2], [3, 4]])
B=np.array([1, 2, 3])
A+B

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [15]:
A=np.array([[1, 2, 3], [4, 5, 6]])
B=np.array([2])
A+B

array([[3, 4, 5],
       [6, 7, 8]])

In [16]:
A=np.array([[1, 2, 3], [4, 5, 6]])
B=np.array([[2], [4]])
A+B

array([[ 3,  4,  5],
       [ 8,  9, 10]])